// runner 以独立 .mjs 落盘执行(spec §3.1:不用 node -e,绕开 shell 引号嵌套)。
// 约束:本字符串内不得出现反引号或 ${,否则嵌套转义地狱回归。
export const RUNNER_SOURCE: string = [
	'import { readFileSync, writeFileSync } from "node:fs";',
	'import { execSync } from "node:child_process";',
	'',
	'const CONFIG = ".pi-web/status.json";',
	'const RESULT = ".pi-web/status-result.json";',
	'',
	'function firstLine(value) {',
	'  if (value === undefined || value === null) return "";',
	'  return value.toString().split("\\n")[0].slice(0, 120);',
	'}',
	'',
	'const probes = [];',
	'let error;',
	'try {',
	'  const config = JSON.parse(readFileSync(CONFIG, "utf8"));',
	'  if (config === null || config.version !== 1 || !Array.isArray(config.probes)) {',
	'    throw new Error("status.json: version must be 1 with a probes array");',
	'  }',
	'  for (const probe of config.probes) {',
	'    const started = Date.now();',
	'    let ok = null;',
	'    let exitCode = null;',
	'    let detail = "";',
	'    try {',
	'      const stdout = execSync(probe.command, {',
	'        shell: "/bin/bash",',
	'        timeout: probe.timeoutMs ?? 10000,',
	'        stdio: ["ignore", "pipe", "pipe"],',
	'      });',
	'      ok = true;',
	'      exitCode = 0;',
	'      detail = firstLine(stdout);',
	'    } catch (err) {',
	'      if (err.signal) {',
	'        ok = null;',
	'        detail = "timeout/killed (" + err.signal + ")";',
	'      } else {',
	'        ok = false;',
	'        exitCode = typeof err.status === "number" ? err.status : null;',
	'        detail = firstLine(err.stderr) || firstLine(err.stdout) || firstLine(err.message);',
	'      }',
	'    }',
	'    probes.push({ id: probe.id, title: probe.title, group: probe.group, ok, exitCode, detail, durationMs: Date.now() - started });',
	'  }',
	'} catch (err) {',
	'  error = err instanceof Error ? err.message : String(err);',
	'}',
	'',
	'const result = { version: 1, collectedAt: new Date().toISOString(), probes };',
	'if (error !== undefined) result.error = error;',
	'writeFileSync(RESULT, JSON.stringify(result, null, 2));',
	'if (error !== undefined) process.exit(1);',
	'',
].join("\n");
